language: node_js
node_js:
    - "node"
before_script:
  - node ./bin/cake build
  - node ./bin/cake build:parser
  - node ./bin/cake build
  - node ./bin/cake build:inline-runtime
  - node ./bin/cake build:browser
script:
  - node ./bin/cake test
