// Generated by IcedCoffeeScript 108.0.12
(function() {
  exports.transform = function(x, options) {
    return x.icedTransform(options);
  };

  exports.runtime = require('iced-runtime');

}).call(this);
